apiVersion: v1
kind: ReplicationController
metadata:
  name: concourse-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: concourse-web
    spec:
      containers:
      - name: concourse-web
        image: concourse/concourse
        command: ["/usr/local/bin/dumb-init", "/usr/local/bin/concourse", "web"]
        env:
        - name: CONCOURSE_BASIC_AUTH_USERNAME
          valueFrom:
            secretKeyRef:
              name: concourse-secrets
              key: basic-auth-username
        - name: CONCOURSE_BASIC_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: concourse-secrets
              key: basic-auth-password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: concourse-postgresql-secrets
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: concourse-postgresql-secrets
              key: password
        - name: CONCOURSE_SESSION_SIGNING_KEY
          value: /etc/secrets/concourse/session-signing-key
        - name: CONCOURSE_TSA_HOST_KEY
          value: /etc/secrets/concourse/tsa-host-private-key
        - name: CONCOURSE_TSA_AUTHORIZED_KEYS
          value: /etc/secrets/concourse/tsa-authorized-keys
        - name: POSTGRES_HOST
          value: $(CONCOURSE_POSTGRESQL_SERVICE_HOST)
        - name: POSTGRES_PORT
          value: $(CONCOURSE_POSTGRESQL_SERVICE_PORT)
        - name: CONCOURSE_POSTGRES_DATA_SOURCE
          value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/concourse?sslmode=disable
        - name: EXTERNAL_URL
          value: http://$(CONCOURSE_WEB_SERVICE_HOST):$(CONCOURSE_WEB_SERVICE_PORT)
        - name: MY_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: PEER_URL
          value: http://$(MY_IP):$(CONCOURSE_WEB_SERVICE_PORT)
        ports:
        - containerPort: 8080
          name: atc
        - containerPort: 2222
          name: tsa
        volumeMounts:
          - name: concourse-secrets
            mountPath: /etc/secrets/concourse
            readOnly: true
      volumes:
      - name: concourse-secrets
        secret:
          secretName: concourse-secrets
